version: '3.8'

services:
  server:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@database:5432/webhooks
  database:
    image: postgres:15-alpine 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webhooks
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

    

